FIND_PATH(
	SUPER_LU_INCLUDES
	NAMES supermatrix.h
	PATHS ${SUPER_LU_INCLUDE_PATH}
	PATH_SUFFIXES SRC
)
FIND_LIBRARY(
	SUPER_LU_LIBRARIES
	NAMES superlu
	PATHS "${SUPER_LU_LIBRARY_PATH}"
	PATH_SUFFIXES lib lib32 lib64 SRC
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	SuperLU
	DEFAULT_MSG
	SUPER_LU_INCLUDES
	SUPER_LU_LIBRARIES
)

#MARK_AS_ADVANCED(SUPER_LU_INCLDUES SUPER_LU_LIBRARIES)
