FIND_PATH(
	GMP_INCLUDES
	NAMES gmp.h
)
FIND_LIBRARY(
	GMP_LIBRARIES
	NAMES gmp
	PATH_SUFFIXES lib lib32 lib64 SRC
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	GMP FOUND_VAR GMP_FOUND
	REQUIRED_VARS GMP_INCLUDES GMP_LIBRARIES
)

#MARK_AS_ADVANCED(GMP_INCLDUES GMP_LIBRARIES)
