FIND_PATH(
	PYTHON_INCLUDES
	NAMES Python.h
	PATH_SUFFIXES python2.7
)
FIND_LIBRARY(
	PYTHON_LIBRARIES
	NAMES python2.7
	PATH_SUFFIXES lib lib32 lib64
)

IF(PYTHON_INCLUDES AND PYTHON_LIBRARIES)
	SET(CMAKE_REQUIRED_INCLUDES ${PYTHON_INCLUDES})
	SET(CMAKE_REQUIRED_LIBRARIES ${PYTHON_LIBRARIES})
	INCLUDE(CheckCXXSourceCompiles)
	CHECK_CXX_SOURCE_COMPILES(
		"
		#include <Python.h>
		#include <numpy/arrayobject.h>

		int main(int argc, char **argv){
			PyTuple_New(0);

			return 0;
		}"
		PYTHON_COMPILED
	)
	IF(${PYTHON_COMPILED})
		INCLUDE(FindPackageHandleStandardArgs)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS(
			Python FOUND_VAR Python_FOUND
			REQUIRED_VARS PYTHON_INCLUDES PYTHON_LIBRARIES
		)
	ENDIF(${PYTHON_COMPILED})
ENDIF(PYTHON_INCLUDES AND PYTHON_LIBRARIES)

#MARK_AS_ADVANCED(PYTHON_INCLDUES PYTHON_LIBRARIES)
