FIND_LIBRARY(
	ARPACK_LIBRARY
	NAMES arpack
	PATH ${ARPACK_LIBRARY_PATH}
	PATH_SUFFIXES lib lib32 lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ARPACK DEFAULT_MSG ARPACK_LIBRARY)

#MARK_AS_ADVANCED(ARPACK_LIBRARY)
