FIND_LIBRARY(
	OPEN_BLAS_LIBRARY
	NAMES openblas
	PATH ${OPEN_BLAS_LIBRARY_PATH}
	PATH_SUFFIXES lib lib32 lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	OpenBLAS FOUND_VAR OpenBLAS_FOUND
	REQUIRED_VARS OPEN_BLAS_LIBRARY
)

#MARK_AS_ADVANCED(ARPACK_LIBRARY)
