SET(TBTK_VERSION_MAJOR 0)
SET(TBTK_VERSION_MINOR 9)
SET(TBTK_VERSION_PATCH 5)
SET(
	TBTK_VERSION
	${TBTK_VERSION_MAJOR}.${TBTK_VERSION_MINOR}.${TBTK_VERSION_PATCH}
)

ADD_DEFINITIONS(
	-DTBTK_VERSION_MAJOR=${TBTK_VERSION_MAJOR}
	-DTBTK_VERSION_MINOR=${TBTK_VERSION_MINOR}
	-DTBTK_VERSION_PATCH=${TBTK_VERSION_PATCH}
)

INCLUDE(TBTKGitInfo)
