INCLUDE("${CMAKE_CURRENT_LIST_DIR}/TBTKTargets.cmake")

LIST(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules/")

#Detect packages
FIND_PACKAGE(BLAS REQUIRED)
FIND_PACKAGE(LAPACK REQUIRED)
FIND_PACKAGE(HDF5 REQUIRED)
FIND_PACKAGE(ARPACK QUIET)
FIND_PACKAGE(CUDA QUIET)
FIND_PACKAGE(CURL QUIET)
FIND_PACKAGE(FFTW3 QUIET)
FIND_PACKAGE(OpenCV QUIET)
FIND_PACKAGE(OpenMP QUIET)
FIND_PACKAGE(SuperLU QUIET)
FIND_PACKAGE(wxWidgets QUIET)

MESSAGE(${HDF5_LIBRARY_DIRS})

LIST(APPEND TBTK_LIBRARIES "-lTBTK")

IF(ARPACK_FOUND)
	LIST(APPEND TBTK_LIBRARIES "-larpack")
ENDIF(ARPACK_FOUND)

IF(CUDA_FOUND)
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES} -lcudart -lcusparse")
ENDIF(CUDA_FOUND)

IF(CURL_FOUND)
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES} -lcurl")
ENDIF(CURL_FOUND)

IF(FFTW3_FOUND)
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES} -lfftw3")
ENDIF(FFTW3_FOUND)

IF(OpenCV_FOUND)
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES}")
ENDIF(OpenCV_FOUND)

IF(OpenMP_FOUND OR OPENMP_FOUND)
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
ENDIF(OpenMP_FOUND OR OPENMP_FOUND)

IF(SuperLU_FOUND)
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES} -lsuperlu")
	INCLUDE_DIRECTORIES(${SUPER_LU_INCLUDES})
ENDIF(SuperLU_FOUND)

IF(wxWidgets_FOUND)
	INCLUDE(${wxWidgets_USE_FILE})
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${wxWidgets_CXX_FLAGS}")
	SET(TBTK_LIBRARIES "${TBTK_LIBRARIES} ${wxWidgets_LIBRARIES}")
ENDIF(wxWidgets_FOUND)

LIST(APPEND TBTK_LIBRARIES "-lhdf5 -lhdf5_cpp -llapack -lblas")
